dist: trusty
sudo: true

language: cpp

services: docker

notifications:
  email: false

git:
  quiet: true

before_install:
   - sudo git clone --recursive --branch ${TRAVIS_BRANCH} https://github.com/derdoktor667/Flysky-OpenTX-Test-Branch /nv14-build

# ...to speed up travisci let dockerhub supply the image
install:
# - docker build -t derdoktor667/nv14-build ${TRAVIS_BUILD_DIR}
  - docker pull derdoktor667/nv14-build:latest

before_script:
  - export -f travis_nanoseconds
  - export -f travis_time_start
  - export -f travis_time_finish

  - runBuildWithoutFlag() { 
        exitcode=0; 
        travis_time_start; 
        echo "docker run --rm -it -v /nv14-build:/nv14-build derdoktor667/nv14-build";
        docker run --rm -it -v /nv14-build:/nv14-build derdoktor667/nv14-build;
        exitcode=$?;
        echo;
        return $exitcode;
        }

  - runBuildWithFlag() { 
        exitcode=0; 
        travis_time_start; 
        echo "docker run --rm -it -v /nv14-build:/nv14-build -e \"CMAKE_FLAGS=$2\"  derdoktor667/nv14-build";
        docker run --rm -it -v /nv14-build:/nv14-build -e "CMAKE_FLAGS=$2" derdoktor667/nv14-build;
        exitcode=$?;
        echo;
        return $exitcode;
        }

  - runBuild() { 
        if [ "$2" ]; then runBuildWithFlag $1 "$2"; else runBuildWithoutFlag $1; fi; }

script:
  - runBuild "NV14.Default"
