dist: trusty
sudo: true
language: cpp

services: docker

notifications:
  email: false

before_install:
#  - sudo ln -s /Flysky-OpenTX-Test-Branch /nv14-build
   - sudo git clone https://github.com/derdoktor667/Flysky-OpenTX-Test-Branch /nv14-build

install:
  - docker build -t derdoktor667/nv14-build ${TRAVIS_BUILD_DIR}

before_script:
  - export -f travis_nanoseconds
  - export -f travis_time_start
  - export -f travis_time_finish

  - runBuildWithoutFlag() { 
        exitcode=0; 
        travis_time_start; 
        echo "docker run --rm -it -v /nv14-build:/nv14-build derdoktor667/nv14-build";
        docker run --rm -it -v /nv14-build:/nv14-build derdoktor667/nv14-build;
        exitcode=$?;
        echo;
        return $exitcode;
        }

  - runBuildWithFlag() { 
        exitcode=0; 
        travis_time_start; 
        echo "docker run --rm -it -v /nv14-build:/nv14-build -e \"CMAKE_FLAGS=$2\"  derdoktor667/nv14-build";
        docker run --rm -it -v /nv14-build:/nv14-build -e "CMAKE_FLAGS=$2" derdoktor667/nv14-build;
        exitcode=$?;
        echo;
        return $exitcode;
        }

  - runBuild() { 
        if [ "$2" ]; then runBuildWithFlag $1 "$2"; else runBuildWithoutFlag $1; fi; }

script:
  - runBuild "NV14.Default"
